/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package loginvanabby;


import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Personal
 */
public class SeleccionProductos extends javax.swing.JDialog {

    Connection cn;
    private Registro_Venta ventanaPrincipal;

    /**
     * Creates new form SeleccionProductos
     */
    public SeleccionProductos(Registro_Venta principal) throws SQLException {
        super(principal, true);
        this.ventanaPrincipal = principal;
        this.cn = ConexionBD.getConexion();
        initComponents();
        mostrarProducto(0, null);
    }

    // Este constructor alternativo no se usa realmente
    public SeleccionProductos(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        this.cn = ConexionBD.getConexion();
        initComponents();
        mostrarProducto(0, null);
    }

    public void mostrarProducto(int opcionBuscar, String valor) {
        DefaultTableModel tProducto = new DefaultTableModel();
        tProducto.addColumn("ID");
        tProducto.addColumn("Nombre");
        tProducto.addColumn("Descripción");
        tProducto.addColumn("Categoría");
        tProducto.addColumn("Precio");

        String baseSelect = "SELECT p.producto_id, p.nombre, p.descripcion, "
                + "COALESCE(c.nombre_categoria, '') AS categoria, p.precio "
                + "FROM producto p LEFT JOIN categoria c ON p.categoria_id = c.categoria_id";

        String sql;
        if (opcionBuscar == 0 && valor == null) {
            sql = baseSelect;
        } else if (opcionBuscar == 1 && valor != null) {
            sql = baseSelect + " WHERE p.nombre LIKE ?";
        } else if (opcionBuscar == 2 && valor != null) {
            sql = baseSelect + " WHERE c.nombre_categoria = ?";
        } else {
            sql = baseSelect;
        }

        String[] datos = new String[5];
        try {
            PreparedStatement ps = cn.prepareStatement(sql);

            if (opcionBuscar == 1 && valor != null) {
                ps.setString(1, "%" + valor + "%");
            } else if (opcionBuscar == 2 && valor != null) {
                ps.setString(1, valor);
            }

            ResultSet rs = ps.executeQuery();

            // Limpiar la tabla antes de agregar nuevos datos
            tProducto.setRowCount(0);

            while (rs.next()) {
                datos[0] = rs.getString("producto_id");
                datos[1] = rs.getString("nombre");
                datos[2] = rs.getString("descripcion");
                datos[3] = rs.getString("categoria");  // alias from JOIN
                datos[4] = rs.getString("precio");
                tProducto.addRow(datos.clone());
            }

            rs.close();
            ps.close();

            // Actualizar el modelo de la tabla
            TablaProductos.setModel(tProducto);

            // DEBUG: Mostrar cuántas filas se cargaron
            System.out.println("Filas cargadas: " + tProducto.getRowCount());

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Error al cargar productos: " + e.getMessage(),
                    "Error de Base de Datos", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        txtCantidad = new javax.swing.JTextField();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 230, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 244, 228));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 990, -1));

        jLabel1.setFont(new java.awt.Font("Pristina", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Cantidad:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, -1, -1));
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 220, -1));

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 1030, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int fila = TablaProductos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un producto");
            return;
        }

        if (TablaProductos.getValueAt(fila, 0) == null) {
            JOptionPane.showMessageDialog(this, "No hay datos en la fila seleccionada");
            return;
        }

        try {
            // Obtener precio del producto
            double precio = Double.parseDouble(TablaProductos.getValueAt(fila, 4).toString());

            // Validar que txtCantidad no esté vacío
            String cantidadTexto = txtCantidad.getText().trim();
            if (cantidadTexto.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ingrese una cantidad");
                txtCantidad.requestFocus();
                return;
            }

            int cantidad = Integer.parseInt(cantidadTexto);

            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0");
                txtCantidad.requestFocus();
                return;
            }

            // Calcular subtotal del producto
            double totalProducto = precio * cantidad;

            // Actualizar el total en la ventana principal
            if (ventanaPrincipal != null) {
                System.out.println("Actualizando total con: $" + String.format("%.2f", totalProducto)); 

                ventanaPrincipal.actualizarTotal(totalProducto);

                JOptionPane.showMessageDialog(this,
                        "Producto agregado exitosamente\n\n"
                        + "Producto: " + TablaProductos.getValueAt(fila, 1) + "\n"
                        + "Precio unitario: $" + String.format("%.2f", precio) + "\n"
                        + "Cantidad: " + cantidad + "\n"
                        + "Subtotal: $" + String.format("%.2f", totalProducto),
                        "Producto Agregado",
                        JOptionPane.INFORMATION_MESSAGE);

                // Limpiar el campo de cantidad después de agregar
                txtCantidad.setText("");
                txtCantidad.requestFocus();

            } else {
                System.out.println("ERROR: ventanaPrincipal es NULL"); 
                JOptionPane.showMessageDialog(this,
                        "Error: No se puede actualizar el total.\nLa conexión con la ventana principal falló.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese una cantidad válida (solo números enteros)",
                    "Error de validación",
                    JOptionPane.WARNING_MESSAGE);
            txtCantidad.requestFocus();
            txtCantidad.selectAll();
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            try {
                SeleccionProductos dialog = new SeleccionProductos(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
